# 
name: Test static website with SSL Labs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
          
      - name: Checkout SSL Labs
        uses: actions/checkout@v3
        with:
          repository: ssllabs/ssllabs-scan
          path: './ssllabs-scan'
      
      - name: Run SSL Labs
        run: |
          set +e
          ls -la ./ssllabs-scan
          chmod u+x ./ssllabs-scan/ssllabs-scan-v3.go
          go run ssllabs-scan/ssllabs-scan-v3.go --grade --quiet https://fyzel.com/
