# This is a basic workflow to help you get started with Actions

name: Test TLS v1.0 - expect no support

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-tls-v1.0"
  test-tls-v1.0:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run curl to test TLS v1.0
        run: |
          echo "Running curl to test TLS 1.0"
          set +e
          /usr/bin/curl --tlsv1.0 --tls-max 1.0 https://fyzel.com/ -s -o /dev/null
          if [[ $? -ne 0 ]]; then
            exit 0
          else
            exit 1
          fi
